[build]
publish = "public"
command = "hugo"

[build.environment]
  HUGO_VERSION = "0.152.2"
  HUGO_ENABLEGITINFO = "true"
  HUGO_EXTENDED = "true"

[context.production.environment]
HUGO_VERSION = "0.152.2"

[[redirects]]
from = "/channels/"
to = "/resources/channels/"
status = 301
